version: "3.9"
services:
  ppnext:
    build: .
    ports:
      - 38080:38080
    environment:
      MONGODB_URI: placeholder
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=ppnextdb
      - MONGO_INITDB_ROOT_USERNAME=ppnext
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - ./mongo/initdb.d:/docker-entrypoint-initdb.d:ro
      - ./mongo/data/db:/data/db
      - ./mongo/data/log:/var/log/mongodb

